### ISSUE TITLE
[Firefox] window.web3 is undefined 

### ISSUE THREAD

**Issue by ilanolkies** [rnsdomains/rns-manager-react#119]
If Metamask or similar software is not installed, the website throws out such an error.

From: https://github.com/rnsdomains/rns-rskregistrar/issues/44

**Comment by jessgusclark** [comment]
## Not reproducible 

I tested the following in all three environments.

## Firefox:

- Disable Firefox, refresh browser
- Console line: window.web3 returns `undefined`
- Navigate to the manager (localhost, testnet, mainnet)
- Search and resolve work without issue. Registering or logging in informs user to install metamask.

I suspect this issue was fixed when the [“Lock Manager with wrong network” PR #107](https://github.com/rnsdomains/rns-manager-react/pull/107) was merged. Or it was fixed with the bug that was found in [PR 144](#https://github.com/rnsdomains/rns-manager-react/pull/144), when the routes.js file was changed.
