### ISSUE TITLE
Persist if register was triggered

### ISSUE THREAD

**Issue by ilanolkies** [rnsdomains/rns-manager-react#132]
Steps to reproduce:
1. Search for an available domain
2. Register
3. Submit commitment
4. Wait and click on register
5. _Reload. Now the registration starts back from commitment._

**Comment by jessgusclark** [comment]
@ilanolkies 

I can't reproduce this error. I believe this was fixed with some of the recent commits regarding localstorage or with the redesign of the registration process.

A user can quit at any step now and with the local storage, pick up where they left off. The only exception is if the user clears their localstorage.

**Comment by ilanolkies** [comment]
Clarification: confirm register, reload screen before it is confirmed.
